version: "3"

services:
  blog:
    build: .
    platform: linux/amd64
    volumes:
      - .:/app
    expose:
      - "8802"
    ports:
      - "8802:8802"
    entrypoint: /app/scripts/start_dev_server.sh
    working_dir: /app
