let u = import("../utils.gr")


fn aboutme() {
    return ["div", ["class", "aboutme"], [
        ["p", [], "Hi folks!"],
        ["p", [], "I'm Miguel. Here I write mainly about programming and side projects."],
        ["p", [], [
            "I've written my own programming language called Grotsky, and it's ",
            ["a", ["href", "https://mliezun.github.io/2023/11/23/grotsky-rust-part3.html", "target", "_blank"], "implemented in Rust"],
            ". This blog's engine is written with Grotksy and generates static HTML files."
        ]]
    ]]
}

fn now() {
	return [
		["div", [], [
			"Last updated on 2025-03-20.",
			["ul", [], [
				["li", [], [
					"Working on ",
					["a", ["href", "https://github.com/mliezun/caddy-snake", "target", "_blank"], [
						"https://github.com/mliezun/caddy-snake",
					]],
					". A plugin for the Caddy proxy that embeds the Python interpreter.",
				]],
				["li", [], [
					"Also building an AI-enabled database editor.",
				]],
				["li", [], [
					"I've built Grotsky, a toy programming language made with Rust. Sometimes I still poke around with it.",
				]],
				["li", [], [
					"Still training to run a 42km marathon. I use a Coros watch, it's awesome.",
				]],
				["li", [], [
					"Moved to Paris, France 6 months ago. Recently to a new apartment.",
				]],
				["li", [], [
					"Learning French.",
				]],
				["li", [], [
					"Working as a Software Engineer at Gencove, building the future of Genome Sequencing."
				]],
			]],
			["div", [], [
				"See more about the /now project here:",
				["a", ["href", "https://nownownow.com/", "target", "_blank"], [
					"https://nownownow.com/",
				]],
			]],
		]],
	]
}

fn build_now() {
    return [
        aboutme(),
        [
			"div",
			[],
			now()
        ],
    ]
}
